
language: node_js
node_js:
  - 4.2.2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install:
    # Use GCC 4.8 if it's available
  - 'if [ ! `which gcc-4.8` == "" ]; then export CXX=g++-4.8 && export CC=gcc-4.8; fi'
  - npm install -g grunt-cli
  #temp fix for https://github.com/kss-node/kss-node/issues/236
  - npm install -g git://github.com/RobLoach/kss-node.git#xdemo
install: npm install
before_script: grunt dist --verbose
script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then bash ./deploy-ghpages.sh; fi
env:
  global:
    - GH_REF: github.com/Teleopti/styleguide.git
    - secure: d9ejf1F4Q+kIhKVfaReYlW3itLeMmQzcuJH4vM/LffzJb/PusyI+mMBmo4Bc4h3GmkJEjCb78nrxjzRFZeG3C7C4jOgg2NGGIwQzpHoKcziwmfpX8BgFTnBU6VlmLUBnNxOINppLV6glMR0kHK6o/KLrKC56xKzHX4/yYrXcPdQ=
